apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: default
  name: demo-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-cron
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo 'I am Busy'
          restartPolicy: OnFailure
  suspend: false