apiVersion: v1
kind: Pod
metadata:
  name: demo-secret-usage
spec:
  containers:
  - name: demo-secret
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: demo-db-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: demo-db-secret
            key: password
  restartPolicy: Never