apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: demo-nginx-deployment
  labels:
    app: demo-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-nginx
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nodeport-svc
  labels:
    app: demo-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80    # if not define then default is same as port.
      nodePort: 30001   # if not define then add port based on nodePort range
  selector:
    app: demo-nginx