apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-daemonset-dev
  namespace: default
  labels:
    app: demo-daemon-dev
spec:
  selector:
    matchLabels:
      name: demo-daemon-dev
  template:
    metadata:
      labels:
        name: demo-daemon-dev
    spec:
      containers:
      - name: demo-daemon-dev
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; sleep 500
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
      nodeSelector:
        env: "dev"